apiVersion: v1
kind: Service
metadata:
  labels:
    app: "secure-server"
  name: "secure-server"
spec:
  ports:
  - name: "grpc"
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: "secure-server"
  loadBalancerIP: "104.196.133.47"
  type: LoadBalancer
